// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBuIT1L7h5uD1YWpV6kyyh1sV0f4Mjq9c',
    appId: '1:470409363636:web:d60f6d7bab2af03ac697e1',
    messagingSenderId: '470409363636',
    projectId: 'yt-len-4610b',
    authDomain: 'yt-len-4610b.firebaseapp.com',
    storageBucket: 'yt-len-4610b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEJ94dB_SMG-zHRcWdml8kviXFv88y9Y',
    appId: '1:470409363636:android:5e3e8b898b620fcec697e1',
    messagingSenderId: '470409363636',
    projectId: 'yt-len-4610b',
    storageBucket: 'yt-len-4610b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_pKMgCWAZucSvsHmv3mzaBmHynZ_mSf4',
    appId: '1:470409363636:ios:53fbb279aa49f704c697e1',
    messagingSenderId: '470409363636',
    projectId: 'yt-len-4610b',
    storageBucket: 'yt-len-4610b.appspot.com',
    iosBundleId: 'com.example.lastMoment',
  );
}
